### ISSUE TITLE
Configure File Extension in config

### ISSUE THREAD

**Issue by maxstrebel** [boldenamsterdam/htmlcache#16]
I have a rather rare use case, where we cache files on a server and deploy it on an instance without Craft (it's weird). That said, would it be an option to add a config parameter for the file extension, so one can opt to use .php instead of .html?

Or should I rather fork?

https://github.com/boldenamsterdam/htmlcache/blob/830ad058eff60c3f2f7f00d88d252e89ae080b0b/src/services/HtmlcacheService.php#L226

**Comment by boldenamsterdam** [comment]
Hi @maxstrebel,

I don't think this option will ever become part of the plugin. You could use .htaccess to read .html files when .php files are requested or rename the files on creation. 
Otherwise you can always fork the project.

**Comment by maxstrebel** [comment]
Thx!
