### ISSUE TITLE
CLI error

### ISSUE THREAD

**Issue by tfortier** [boldenamsterdam/htmlcache#2]
When the plugin is installed any CLI command returns an error. Disabling the plugin fixes the issue.

Example command : `./craft`
Error : `Exception 'yii\base\UnknownMethodException' with message 'Calling unknown method: craft\console\Request::getParam()'`

This seems to have a link with [https://github.com/craftcms/element-api/issues/80](url) but I'm not exactly sure.

**Comment by boldenamsterdam** [comment]
It looks related indeed. I have a craft installation with the plugin enabled and `./craft` command works fine. Can you tell me how to reproduce the error?

**Comment by tfortier** [comment]
Hum, weird. Maybe it's the fact I'm on Windows? Craft CMS seems to hate running on Windows for some reason.

**Comment by boldenamsterdam** [comment]
Not sure. I pushed an update to dev-master with a possible fix. can you check if your issue has been fixed?
