### ISSUE TITLE
Configuration?

### ISSUE THREAD

**Issue by kieronkeenan** [boldenamsterdam/htmlcache#3]
Hi there,

Just wondering - other than installing and enabling the plugin, is there any other configuration necessary? Any that needs to be wrapped in a cache tag? Are the cached html files stored in storage/runtime/htmlcache/?

Not seeing much improvement on my site and I also can't find where the files are stored so I'm not sure I have it configured correctly.

Any help appreciated!

**Comment by boldenamsterdam** [comment]
Hello,

it should work out of the box if the plugin is enabled. If you work with DevMode enabled then you should enable the `Force On` setting. No special cache tags needed. If the plugin works correctly you will see the cached files in storage/runtime/htmlcache/ folder.

To check the performance improvement check the loading time of the page with your browser inspector. There you will be able to see the performance in ms.
