### ISSUE TITLE
Can't unistall plugin

### ISSUE THREAD

**Issue by wornout** [boldenamsterdam/htmlcache#39]
I cannot delete the plugin from Craft.
Issue on Craft 3.7.25.1

**Comment by wornout** [comment]
@olivierbon sorry but applying the changes in local files doesn't solve the problem...

Error: Class "bolden\htmlcache\records\HtmlCacheCacheRecord" not found in E:\sites\CraftCMS\vendor\bolden\htmlcache\src\services\HtmlcacheService.php:250

**Comment by olivierbon** [comment]
@wornout Did you correctly rename  `src/records/HtmlCacheCachesRecord.php` → `src/records/HtmlCacheCacheRecord.php` (remove the `s`)?

**Comment by wornout** [comment]
@olivierbon didn't see it! Removed. Thank you!
